version: '2'

services:
  webserver:
    extends:
      file: ./docker/nginx/docker-compose.yml
      service: webserver
    ports:
      - "8088:80"
  php:
    extends:
      file: ./docker/php/7.1/docker-compose.yml
      service: php
    container_name: erdiko_php
